// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbmsjlctxoaffrlitcyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibXNqbGN0eG9hZmZybGl0Y3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODMzNDYsImV4cCI6MjA2MTg1OTM0Nn0.dV-z0ofWpl1l9tSmXmgfarHW8PGQCesTZAYXARfq1dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);